/**
 * Writes tools/tokens.generated.css from src/lib/tokens.ts.
 *
 * The jigs are standalone HTML opened over file://, so they cannot import the
 * token module. Before this they each carried their own copy of the palette
 * with a comment saying the values were "lifted from the live build" — which is
 * exactly how three jigs in two repos drifted onto a retired terracotta.
 *
 * The output is committed rather than gitignored, so opening a jig directly in
 * a browser still renders correctly. `pnpm tokens:check` asserts it is current,
 * the way a lockfile is checked, and `capture.sh` regenerates it before every
 * render.
 *
 * Run: node tools/gen-tokens.mjs        (or --check to verify without writing)
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const HERE = dirname(fileURLToPath(import.meta.url));
const OUT = join(HERE, "tokens.generated.css");

const { PALETTE, DARK_BANNER, GRID_LINE } = await import(
  join(HERE, "../src/lib/tokens.ts")
);

const body = `/*
 * GENERATED by tools/gen-tokens.mjs from src/lib/tokens.ts. Do not edit.
 *
 * Regenerate with \`node tools/gen-tokens.mjs\`; \`pnpm tokens:check\` fails if
 * this file is stale.
 */
:root {
${Object.entries(PALETTE)
  .map(([k, v]) => `  --color-${k}: ${v};`)
  .join("\n")}
  --grid-line: ${GRID_LINE};

  /* The site's real grid unit, from globals.css. */
  --grid-cell: 64px;
}

/*
 * The GitHub banner's dark ground. Derived for its own ground rather than
 * inverted from the light set — see the DARK_BANNER comment in tokens.ts.
 */
[data-variant="dark"] {
${Object.entries(DARK_BANNER)
  .map(([k, v]) => `  --color-${k}: ${v};`)
  .join("\n")
  .replace("--color-grid:", "--grid-line:")}
}
`;

if (process.argv.includes("--check")) {
  let current = "";
  try {
    current = readFileSync(OUT, "utf8");
  } catch {
    /* missing counts as stale */
  }
  if (current !== body) {
    console.error(
      "✗ tools/tokens.generated.css is stale — run node tools/gen-tokens.mjs"
    );
    process.exit(1);
  }
  console.log("  tools/tokens.generated.css is current");
} else {
  writeFileSync(OUT, body);
  console.log("wrote tools/tokens.generated.css");
}
