import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath, pathToFileURL } from "node:url";
import { dirname, join } from "node:path";

const HERE = dirname(fileURLToPath(import.meta.url));
export const TOKENS_CSS = join(HERE, "tokens.generated.css");

export async function renderTokensCss() {
  const { PALETTE, DARK_BANNER, GRID_LINE } = await import(
    join(HERE, "../src/lib/tokens.ts")
  );
  const vars = (obj, rename = {}) =>
    Object.entries(obj)
      .map(([k, v]) => `  --${rename[k] ?? `color-${k}`}: ${v};`)
      .join("\n");

  return `/* GENERATED by tools/gen-tokens.mjs from src/lib/tokens.ts. Do not edit. */
:root {
${vars(PALETTE)}
  --grid-line: ${GRID_LINE};
  --grid-cell: 64px;
}

[data-variant="dark"] {
${vars(DARK_BANNER, { grid: "grid-line" })}
}
`;
}

export function tokensCssIsCurrent(expected) {
  try {
    return readFileSync(TOKENS_CSS, "utf8") === expected;
  } catch {
    return false;
  }
}

if (import.meta.url === pathToFileURL(process.argv[1]).href) {
  writeFileSync(TOKENS_CSS, await renderTokensCss());
  console.log("wrote tools/tokens.generated.css");
}
